export type ParsedRecipe = {
  id: string
  title: string
  caption: string
  image: string
}

export type ParsedAnswer = {
  text: string
  items: ParsedRecipe[]
}

export function parseAnswerXml(xml: string): ParsedAnswer | null {
  try {
    // DOMParser is safe here because the XML is generated by *your* backend
    const parser = new DOMParser()
    const doc = parser.parseFromString(xml, "application/xml")

    // Handle malformed XML
    if (doc.querySelector("parsererror")) {
      console.error("XML parse error")
      return null
    }

    // ---- Extract text ----
    const textNode = doc.querySelector("answer > text")
    const text = textNode?.textContent?.trim() ?? ""

    // ---- Extract items ----
    const itemNodes = Array.from(doc.querySelectorAll("answer > items > item"))

    const items: ParsedRecipe[] = itemNodes.map((item) => ({
      id: item.querySelector("id")?.textContent?.trim() ?? "",
      title: item.querySelector("title")?.textContent?.trim() ?? "",
      caption: item.querySelector("caption")?.textContent?.trim() ?? "",
      image: item.querySelector("image")?.textContent?.trim() ?? "",
    })).filter(item => item.id && item.title)

    return { text, items }
  } catch (err) {
    console.error("Failed to parse XML:", err)
    return null
  }
}