"use client";

export default function TermsOfUse() {
  return (
    <div className="flex flex-col items-center justify-start min-h-screen p-6 pt-9 bg-white">
      <div className="w-full max-w-3xl space-y-8">
        {/* Header */}
        <div className="space-y-4">
          <p className="text-3xl text-[#98E14D] font-black tracking-tighter">Hands</p>
          <h1 className="text-5xl font-black text-black tracking-tighter leading-none">Terms of Use</h1>
          <p className="text-lg text-gray-600">Updated: 18 November 2025</p>
        </div>

        {/* Content */}
        <div className="space-y-8 text-black">
          <p className="text-lg leading-relaxed">
            Thank you for using Hands! These Terms of Use apply to your use of Hands’ consumer
            services—including any AI features, creative tools, software applications, and
            websites (collectively, the “Services”). These Terms form an agreement between you
            and Hands, and they include our Service Terms as well as important provisions
            related to dispute resolution through arbitration. By using our Services, you agree
            to these Terms. Our Privacy Policy explains how we collect and use personal
            information. Although it is not part of these Terms, it is an important document
            you should review.
          </p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Who we are</h2>
          <p className="text-lg leading-relaxed">Hands is an AI company. Our mission is to intuitively understand human taste and build software that is useful for anyone that cooks.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Registration and access</h2>
          <p className="text-lg leading-relaxed font-semibold">Minimum age.</p>
          <p className="text-lg leading-relaxed">You must be at least 13 years old, or the minimum age required in your country, to consent to use the Services. If you are under 18, you must have permission from your parent or legal guardian to use the Services.</p>

          <p className="text-lg leading-relaxed font-semibold">Registration.</p>
          <p className="text-lg leading-relaxed">To use our Services, you must provide accurate and complete information when creating an account. You may not share your account credentials or allow anyone else to access your account. You are responsible for all activities that occur under your account. If you create an account or use the Services on behalf of another individual or organization, you must have the legal authority to accept these Terms on their behalf.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Using our Services</h2>
          <p className="text-lg leading-relaxed font-semibold">What you can do</p>
          <p className="text-lg leading-relaxed">Subject to your compliance with these Terms, you may access and use the Services provided by Hands. When using our Services, you must follow all applicable laws as well as any documentation, guidelines, usage rules, or policies that Hands makes available to you.</p>

          <p className="text-lg leading-relaxed font-semibold">What you cannot do</p>
          <ul className="space-y-3 text-lg leading-relaxed list-disc pl-6">
            <li>Use the Services in any way that infringes, misappropriates, or violates the rights of others.</li>
            <li>Modify, copy, lease, sell, or distribute any part of the Services.</li>
            <li>Attempt to reverse engineer, decompile, or discover the source code or underlying components of the Services.</li>
            <li>Automatically or programmatically extract data or Output.</li>
            <li>Present Output generated by our Services as human-generated when it is not.</li>
            <li>Interfere with or attempt to bypass protections like rate limits or security measures.</li>
            <li>Use Output to develop or improve competing models.</li>
          </ul>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Software</h2>
          <p className="text-lg leading-relaxed">Some Services may allow you to download software—such as mobile applications—which may update automatically. Certain components may include open-source code governed by separate licenses.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Corporate domains</h2>
          <p className="text-lg leading-relaxed">If you create an account using an organization-owned email, your account may be transferred to that organization.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Third-party Services</h2>
          <p className="text-lg leading-relaxed">Our Services may include or rely on third-party integrations subject to their own terms. Hands is not responsible for them.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Feedback</h2>
          <p className="text-lg leading-relaxed">By providing feedback, you agree Hands may use it without restriction or compensation.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Content</h2>
          <p className="text-lg leading-relaxed font-semibold">Your content</p>
          <p className="text-lg leading-relaxed">You may provide Input and receive Output. You are responsible for ensuring your Content complies with laws and these Terms.</p>

          <p className="text-lg leading-relaxed font-semibold">Ownership of content</p>
          <ul className="space-y-3 text-lg leading-relaxed list-disc pl-6">
            <li>You retain ownership of your Input.</li>
            <li>You own the Output generated for you.</li>
            <li>Hands assigns to you any rights it may have in your Output.</li>
          </ul>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Accuracy</h2>
          <p className="text-lg leading-relaxed">Output may be incomplete, inaccurate, or inappropriate. You agree not to rely on Output as a sole source of truth, especially in areas with legal, financial, medical, or similar consequences.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Our IP rights</h2>
          <p className="text-lg leading-relaxed">Hands and its affiliates own all rights to the Services, including design, models, and underlying technology.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Paid Accounts</h2>
          <p className="text-lg leading-relaxed font-semibold">Billing</p>
          <p className="text-lg leading-relaxed">If you purchase Services, you must provide accurate billing information. Subscriptions renew automatically unless cancelled.</p>

          <p className="text-lg leading-relaxed font-semibold">Cancellation</p>
          <p className="text-lg leading-relaxed">You may cancel at any time. Payments are non-refundable unless required by law.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Termination and Suspension</h2>
          <p className="text-lg leading-relaxed">Hands may suspend or terminate your account for violating these Terms or creating risk. You may appeal suspensions.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Discontinuation of Services</h2>
          <p className="text-lg leading-relaxed">Hands may discontinue some or all Services with advance notice.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Disclaimer of Warranties</h2>
          <p className="text-lg leading-relaxed">THE SERVICES ARE PROVIDED “AS IS.” HANDS DISCLAIMS ALL WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>

          <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Limitation of Liability</h2>
          <p className="text-lg leading-relaxed">TO THE MAXIMUM EXTENT PERMITTED BY LAW, HANDS IS NOT LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS OR DATA.</p>

          <div className="space-y-4">
            <p className="text-lg leading-relaxed font-semibold">OUR TOTAL LIABILITY TO YOU UNDER THESE TERMS WILL NOT EXCEED THE GREATER OF: THE AMOUNT YOU PAID FOR THE SERVICE GIVING RISE TO THE CLAIM IN THE 12 MONTHS PRIOR TO THE EVENT, OR ONE HUNDRED DOLLARS (USD $100).</p>
            <p className="text-lg leading-relaxed">Some jurisdictions do not allow certain warranty disclaimers or liability limitations. In those locations, these Terms apply only to the fullest extent allowed by local law. The affiliates, suppliers, licensors, and distributors of Hands are intended third-party beneficiaries of this section.</p>
          </div>

          <div className="space-y-6 pt-6">
            <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Indemnity</h2>
            <p className="text-lg leading-relaxed">If you are a business or organization, you agree—where permitted by law—to indemnify and hold Hands, its affiliates, and its personnel harmless from all costs, liabilities, damages, and expenses (including attorneys’ fees) arising from any third-party claim related to your use of the Services or Content, or your violation of these Terms.</p>
          </div>

          <div className="space-y-6 pt-6">
            <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Dispute Resolution</h2>
            <p className="text-lg leading-relaxed font-semibold">THE FOLLOWING ARBITRATION AND CLASS ACTION WAIVER TERMS APPLY BETWEEN YOU AND HANDS:</p>

            <h3 className="text-xl font-bold tracking-tight">Mandatory Arbitration</h3>
            <p className="text-lg leading-relaxed">You and Hands agree to resolve all disputes arising out of or relating to these Terms or the Services (“Disputes”) through final and binding arbitration, regardless of when the claim arose. You may opt out within 30 days of creating your account or within 30 days of updates to these terms by using the opt-out form in our Help Center.</p>

            <h3 className="text-xl font-bold tracking-tight">Informal Resolution</h3>
            <p className="text-lg leading-relaxed">Before filing a formal claim, both parties agree to attempt resolving the Dispute informally. If not resolved within 60 days, either party may initiate arbitration.</p>

            <h3 className="text-xl font-bold tracking-tight">Arbitration Forum</h3>
            <p className="text-lg leading-relaxed">Arbitration will be administered by National Arbitration and Mediation (NAM). The Federal Arbitration Act governs these terms.</p>

            <h3 className="text-xl font-bold tracking-tight">Arbitration Procedures</h3>
            <p className="text-lg leading-relaxed">Arbitration will be conducted by videoconference when possible, or in your county of residence if in-person is required. A single qualified arbitrator will preside.</p>

            <h3 className="text-xl font-bold tracking-tight">Exceptions</h3>
            <p className="text-lg leading-relaxed">Arbitration is not required for small-claims court, or for requests involving intellectual property or unauthorized use of the Services.</p>

            <h3 className="text-xl font-bold tracking-tight">Class and Jury Trial Waivers</h3>
            <p className="text-lg leading-relaxed">You and Hands agree that all disputes must be resolved individually, with no class or representative actions permitted. Both parties waive any right to a jury trial.</p>

            <h3 className="text-xl font-bold tracking-tight">Batch Arbitration</h3>
            <p className="text-lg leading-relaxed">If 25 or more similar claims are filed within 90 days, they may be grouped into batches of up to 50 and arbitrated together.</p>

            <h3 className="text-xl font-bold tracking-tight">Severability</h3>
            <p className="text-lg leading-relaxed">If any part of this section is deemed unenforceable, the rest remains in effect—except where unenforceability would allow class-wide arbitration or litigation.</p>
          </div>

          <div className="space-y-6 pt-6">
            <h2 className="text-3xl font-extrabold tracking-tighter leading-none">Copyright Complaints</h2>
            <p className="text-lg leading-relaxed">If you believe your intellectual property rights have been infringed, please send notice to:</p>
            <p className="text-lg leading-relaxed font-semibold">Hands<br/>Attn: General Counsel / Copyright Agent<br/>74 Manning Avenue<br/>Toronto, Ontario M6J 2K5<br/>Canada</p>
            <p className="text-lg leading-relaxed">Your notice must include: your signature; identification of the copyrighted work; location of infringing material; your contact information; and a statement of good-faith belief and accuracy under penalty of perjury.</p>
          </div>

          <div className="space-y-6 pt-6 pb-10">
            <h2 className="text-3xl font-extrabold tracking-tighter leading-none">General Terms</h2>

            <h3 className="text-xl font-bold tracking-tight">Assignment</h3>
            <p className="text-lg leading-relaxed">You may not transfer or assign your rights or obligations under these Terms. Hands may assign its rights or obligations to any affiliate or successor.</p>

            <h3 className="text-xl font-bold tracking-tight">Changes to These Terms or the Services</h3>
            <p className="text-lg leading-relaxed">Hands may update these Terms or the Services as needed. Materially adverse changes will be communicated at least 30 days in advance.</p>

            <h3 className="text-xl font-bold tracking-tight">Delay in Enforcement</h3>
            <p className="text-lg leading-relaxed">Failure to enforce any part of these Terms is not a waiver. If any provision is invalid, the rest remains in effect.</p>

            <h3 className="text-xl font-bold tracking-tight">Trade Controls</h3>
            <p className="text-lg leading-relaxed">You must comply with all export and sanctions laws. The Services may not be used in restricted jurisdictions.</p>

            <h3 className="text-xl font-bold tracking-tight">Entire Agreement</h3>
            <p className="text-lg leading-relaxed">These Terms constitute the entire agreement between you and Hands.</p>

            <h3 className="text-xl font-bold tracking-tight">Governing Law</h3>
            <p className="text-lg leading-relaxed">These Terms are governed by the laws of Ontario, Canada. Unless arbitration applies, all proceedings must be brought in Toronto, Ontario.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
